# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-security}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cyril David"]
  s.date = %q{2010-04-29}
  s.description = %q{For use with Sinatra + Monk + OHM}
  s.email = %q{cyx.ucron@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "examples/classic.rb",
     "examples/views/home.haml",
     "examples/views/login.haml",
     "lib/sinatra/security.rb",
     "lib/sinatra/security/helpers.rb",
     "lib/sinatra/security/identification.rb",
     "lib/sinatra/security/password.rb",
     "lib/sinatra/security/user.rb",
     "lib/sinatra/security/validations.rb",
     "sinatra-security.gemspec",
     "test/helper.rb",
     "test/test_password.rb",
     "test/test_sinatra-security.rb",
     "test/test_sinatra_security_helpers.rb",
     "test/test_validations.rb",
     "views/login.haml"
  ]
  s.homepage = %q{http://github.com/cyx/sinatra-security}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Sinatra authentication extension}
  s.test_files = [
    "test/helper.rb",
     "test/test_password.rb",
     "test/test_sinatra-security.rb",
     "test/test_sinatra_security_helpers.rb",
     "test/test_validations.rb",
     "examples/classic.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

